### ISSUE TITLE
Gracefully handle API rate limits on composer provision

### ISSUE THREAD

**Issue by dhensby** [BetterBrief/vagrant-skeleton#71]
When lots of provisioning goes on we can hit the GH API limit and the provisioning goes very slowly.

**Comment by Firesphere** [comment]
Try using --prefer-dist, that shouldn't hit the rate limit if I'm not mistaken.

**Comment by dhensby** [comment]
@Firesphere having the VCS is pretty nice and important if you're using the machine for core contributions  - though I suppose that doesn't have to be the default...

**Comment by willmorgan** [comment]
I would prefer to use `--prefer-dist`. If you're doing core contributions it's easy to pull down the git refs and then version control that way.

**Comment by dhensby** [comment]
That's true... I guess we shouldn't have the box be default set up for nice core contribs its for a base site

**Comment by Firesphere** [comment]
As long as you keep using composer, it doesn't matter if you use --prefer-dist. Because the refs are kept in the lockfile, updates are installed just as easy.

Although... With prefer dist, the original installation is removed and the new one then downloaded and installed, which is a bit more work for the system, than just updating from actual git.

Having said that, I wouldn't mind a prefer-dist as default. Things I would do on the core, would be on a separate machine where I would setup a core with git anyway, to prevent core work and actual websites getting mixed up.
